version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: ts
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6969:5432"